web/router.ex
defmodule App.Router do
  use App.Web, :router

  pipeline :browser do
    plug :accepts, ["html", "json"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug App.Banner, ""
    plug App.Cookie, ""
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", App do
    pipe_through :browser

    get "/", HomepageController, :index
    post "/", HomepageController, :show
    get "/filter", HomepageController, :filtered_show
    post "/submit", SubmitController, :submit
    post "/like/:article_id", LikesController, :like
    post "/dislike/:article_id", LikesController, :dislike
    get "/article/:id", ArticleController, :show
    get "/styleguide", StyleGuideController, :index
    get "/coming-soon", ComingSoonController, :index
    get "/feedback", FeedbackController, :index
    post "/feedback", FeedbackController, :post
    get "/crisis", CrisisController, :index
    post "/search", HomepageController, :search
    get "/sleep", LandingPageController, :index
    get "/sleep/tips", LandingPageController, :index
    get "/events/grenfell", LandingPageController, :index
    get "/sleep-and-stress", LandingPageController, :index
    get "/sleep-and-mind-racing", LandingPageController, :index
    get "/sleep/talk-about-it", LandingPageController, :index
    get "/:page", StaticController, :index
    # Default route - will match any page - must stay at bottom
  end

  # Other scopes may use custom stacks.
  # scope "/api", App do
  #   pipe_through :api
  # end
end

web/controllers/info_controller.ex
defmodule App.InfoController do
  use App.Web, :controller

  import Ecto.Query, only: [from: 2]

  alias App.CMSRepo

  def index(conn, %{"page" => page}) do
    query = from i in "info_infopage",
      join: w in "wagtailcore_page",
      where: i.page_ptr_id == w.id and w.slug == ^page,
      select: %{
        heading: i.heading,
        body: i.body
      }

    data = CMSRepo.one query

    case data do
      nil ->
        conn
        |> put_status(404)
        |> render(App.ErrorView, "404.html")
      _ -> render conn, "index.html", heading: data.heading, body: data.body
    end
  end
end

web/controllers/landing_page_controller.ex
defmodule App.LandingPageController do
  use App.Web, :controller

  def index(conn, _params) do

    path =  case length conn.path_info do
      1 -> List.first conn.path_info
      _ -> Enum.join(conn.path_info, "-")
    end
    # Requires template to have same name as route
    conn
    |> put_layout(false)
    |> render("#{path}.html")
  end
end

web/views/landing_page_view.ex
defmodule App.LandingPageView do
  use App.Web, :view
end

web/templates/article_list/show.html.eex
<h2><%= @tag |> String.capitalize |> String.replace("-", " ") %> Resources</h2>

<%= for resource <- @resources do %>
  <%= if resource[:url] do %>
    <div>
      <h3><%= resource[:heading] %></h3>
      <%= link resource.url, to: resource.url %>
      <div>
        <%= for tag <- resource.tags do %>
          <%= link tag, to: article_list_path(@conn, :show, tag) %>
        <% end %>
      </div>
      <%= raw(resource[:body]) %>
    </div>
  <%= else %>
    <div>
      <%= link resource.heading, to: article_path(@conn, :show, resource.id) %>
    </div>
  <% end %>
<% end %>

web/templates/homepage/email_form.html.eex
<section class="lm-white lm-bg-dark-blue pa1 ph3 pb4 pb5-l" id="email_form">
  <div class="mh3 mv3 w-60-m w-50-l center" id="alpha">
    <h2 class="f4 f4-ns mb0">ALPHA</h2>
    <h2 class="f5 f4-ns mt1">what does it mean?</h2>
    <p>The “alpha” phase is all about testing ideas and gathering feedback from the people that will be using the service.</p>

    <p>Everything you see now can change based on what you think works and doesn’t work, so please let us know!</p>

    <p>Any feedback you give us will be used to improve the content and functionality of the service, as well as the way the service looks</p>
  </div>

  <div id="alphasection" class="lm-dark-blue lm-bg-white mh3 ph3 pv1 ph4-l pv3-l w-60-m w-50-l center tracked relative">
    <%= raw @content.alphatext %>
    <%= form_for @conn, spreadsheet_path(@conn, :submit_email) <> "#email_form", [as: :email], fn f -> %>
      <%= label f, :email, "Email:", class: "db mv1" %>
      <%= email_input(f, :email, class: "br2 pa2 mb2-l mb3 f5 fw3 ba w-100") %>
      <p class="alert ma0 mb4 pa3 ba bw1-ns bg--lm-green b--lm-green" role="alert"><%= get_flash(@conn, :emails) %></p>
      <div class="relative w-100 mt3">
        <%= component "buttons/primary_button", value: "Take part", class: "absolute bottom--1 right-0" %>
      </div>
    <% end %>
  </div>
</section>

web/templates/homepage/index.html.eex
<section class="pt5-plus ph4 ph5-m ph6-l tc lm-white cover lh-copy bg-center" style="background-image:url('<%= @content.hero_image_url %>')">
  <%= component "images/london_minds_logo", class: "w-60 w-15-ns", conn: @conn %>
  <div class="pb5 w-90-ns f1-ns f6 lh-title center">
    <div class="mb4">
      <%= transform_html @content.header, @conn %>
        <%= form_for @conn, homepage_path(@conn, :search) <> "#results", [as: :query], fn f ->  %>
          <%= text_input f, :q, class: "w-50-ns w-100 db center mt1 b--white ba pa1 pa2-ns nunito f5 br1 bg-white-90 focus-lm-orange", placeholder: "Enter search term", "aria-label": "search", value: assigns[:query], id: "query_q_1"  %>
          <%= hidden_input f, :query_string, value: @conn.query_string, id: "query_string_1" %>
          <%= component "buttons/primary_button", value: "Search", class: "mv3" %>
        <% end %>
    </div>
    <%= if @content.video_url && @content.video_url != "" do %>
      <div class="dib homepage_video_container v-mid ml5-l">
        <%= component "youtube_video", url: @content.video_url, class: "h-100 w-100 h7-ns" %>
      </div>
    <% end %>
  </div>
</section>

<section class="w-60-ns w-80 pv2 pv0-ns center">
  <%= transform_html @content.body, @conn %>
</section>

<div id="results" class="relative top--3 o-0"></div>
<section class="pt4 ph4 ph3-m ph3-l blurred_background cover bg-center">
  <%= form_for @conn, homepage_path(@conn, :search) <> "#results", [as: :query], fn f ->  %>
    <div class="w-60-ns center tc tl-ns">
      <div class="tl lm-dark-blue mb2 nunito-bold">I am, or someone I know, is feeling:</div>
        <%= inputs_for f, :topic, [as: :topic], fn fq -> %>
          <%= for link <- @topics do %>
            <div class="dib relative mv2-ns mv1">
              <%= checkbox fq, String.to_atom(link), value: tag_is_selected(assigns[:selected_tags], link), class: "topic-checked-fill absolute o-0" %>
              <%= label fq, String.to_atom(link), class: "b--lm-dark-blue lm-dark-blue ba br2 pl3 pr4 pv2 dib pointer border-box topic-unchecked br-pill" do
                raw("<span>#{remove_hyphen(link)}</span>")
              end %>
            </div>
          <% end %>
        <% end %>

      <%= hidden_input f, :query_string, value: @conn.query_string %>
    </div>
    <div class="tl w-60-ns center relative pb4">
      <%= text_input f, :q, class: "mt1 mr2 w-100 pa2 pl3 mb3 nunito br1 b--white ba bg-white-90 focus-lm-orange", placeholder: "Enter search term", "aria-label": "search", value: assigns[:query] %>
      <%= component "buttons/primary_button", value: "Search", class: "absolute bottom--1 right-0 right"%>
    </div>
  <% end %>
</section>

<section class="tc-ns">
  <%= if assigns[:resources] do %>
    <%= render "show.html", assigns %>
  <% end %>
  <div class="tc">
    <%= component "buttons/primary_button", value: "See More", id: "see_more", class: "dn-important" %>
  </div>
</section>

<%= render "suggestion_form.html", conn: @conn, content: @content %>

<%= component "alpha_section", conn: @conn, content: @content, show_email_submit: true %>


<section class="pv1 ph3 lm-bg-orange tl">
  <a href="/coming-soon" class="link banners">
    <div class="relative">
      <%= transform_html @content.assessment_text, @conn %>
      <p class="absolute right-1 top--1 dn dib-ns b pointer">></p>
    </div>
  </a>
</section>

<section class="pv1 ph3 tl lm-bg-white">
  <a href="/crisis" class="link banners crisis-link">
    <div class="relative">
      <%= transform_html @content.crisis_text, @conn, id: "crisis-link"%>
      <p class="absolute right-1 top--1 dn dib-ns b pointer">></p>
    </div>
  </a>
</section>

<%= component "footer", content: @content, conn: @conn %>

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Google Tag Manager -->
    <script>
      dataLayer = [];
    </script>
    <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
    new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
    j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
    'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
    })(window,document,'script','dataLayer','GTM-PF8GGT7');</script>
    <!-- End Google Tag Manager -->
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-97311089-1', 'auto');

    </script>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>London Minds</title>
    <%= if is_ie8? @conn do %>
      <link rel="stylesheet" href="<%= static_path @conn, "/css/ie8.css" %>">
    <%= else %>
      <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
      <link rel="stylesheet" href="<%= static_path @conn, "/css/app.css" %>">
    <% end %>
    <link rel="icon" href="favicon.png">
  </head>

  <body>
    <!-- Google Tag Manager (noscript) -->
    <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-PF8GGT7"
    height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
    <!-- End Google Tag Manager (noscript) -->
    <div class="container">
      <%= if String.length(@banner) > 0  do %>
        <div class="lm-bg-white pa3 w-100 f6 f5-l f5-m banner segoe fixed top-0 z-5 dt-ns dt--fixed-ns shadow-2" id="beta-banner">
          <div class="dtc-ns w-50-l w-40-m v-mid">
            <%= transform_html @banner, @conn, class: "underline dib", id: "feedback-link" %>
          </div>
          <div class="dtc-ns dn tr v-mid banner_buttons">
            <%= component "buttons/secondary_button", value: "Take self-assessment", to: "/coming-soon", id: "assessment", class: "f6 f7-m", background: "transparent" %>
            <%= component "buttons/secondary_button", value: "Get urgent support", to: "/crisis", class: "crisis-link f6 f7-m", background: "transparent" %>
          </div>
        </div>
      <% end %>
      <p class="alert" role="alert"><%= get_flash @conn, :info %></p>
      <p class="alert" role="alert"><%= get_flash @conn, :error %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path @conn, "/js/app.js" %>"></script>
  </body>
</html>